### ISSUE TITLE
不能自动删除重复文件

### ISSUE THREAD

**Issue by luxueqiang** [ChenglongMa/zoplicate#36] opened 2024-05-05 12:41 UTC
最新版本的zotero beta 不能自动删除重复文件了~ 望修复

**Comment by ChenglongMa** [comment] 2024-05-05 14:27
您好，请问具体怎么复现这个问题？是库里一直存在两个重复条目没法合并吗？

**Comment by vancleve** [comment] 2024-05-10 21:13
I am also seeing this issue. After identifying the duplicated, I select either Keep This or Keep Others and both copies are retained instead of one being deleted.

**Comment by ChenglongMa** [comment] 2024-05-10 23:08
Hi @vancleve,

Thanks for your feedback.
I'll fix it soon.

Best,
Chenglong

**Comment by ChenglongMa** [comment] 2024-05-11 06:03
Hi @luxueqiang and @vancleve,

I have tested on my device, but couldn't reproduce the issue.

Could you please share some configs of your app? For example,

* Which items have been identified as duplicates and cannot be deleted?
  * Could you please select those items and export them as Zotero RDF?
  * ![Snipaste_2024-05-11_16-01-45](https://github.com/ChenglongMa/zoplicate/assets/33501679/01b1e9f7-4ffc-4c45-915e-bfa51c3634db)

* What is your OS version, WinOS or MacOS?
* What is the Zotero version, Zotero 7.0.0-beta.77+adaa61f2c, right?
* What is the Zoplicate version?

Thank you so much for your help!
Best,
Chenglong

**Comment by vancleve** [comment] 2024-05-12 19:03
No prob. Here are two items where the duplicate wasn't deleted:
[dups.rdf.log (RDF file with .log name to upload to github)](https://github.com/ChenglongMa/zoplicate/files/15287374/dups.rdf.log)

Zoplicate 3.0.1
Zotero 7.0.0-beta.77+adaa61f2c
macOS 14.4.1

**Comment by ChenglongMa** [comment] 2024-05-15 13:12
Hi @vancleve and @luxueqiang,

Thanks for your help. I've known how to fix the bug, but I'm traveling overseas, I will release a new version next week.

Thanks for your patience.

Best,
Chenglong

**Comment by ChenglongMa** [comment] 2024-05-16 09:40
Hi @vancleve and @luxueqiang,

The issue has been fixed by Zotero. Please update Zotero (not Zoplicate 😜) to the latest version: 7.0.0-beta.78.

Thanks!

Best regards,
Chenglong

**Comment by vancleve** [comment] 2024-05-16 20:10
I've updated to beta 78 and I'm seeing the same problem, no removing the duplicate.

**Comment by ChenglongMa** [comment] 2024-05-17 05:08
Hi @vancleve,

Could you please show me the error message after importing duplicate items?

You can get the information via Tools -> Developer -> Error console:

![327979646-f7976cf0-5763-4f6f-9573-41470a58216e.png](https://github.com/ChenglongMa/zoplicate/assets/33501679/d7f1be4b-d695-44e2-a71a-50ccca2e0cb6)

Thank you so much for your help!

I will try my best to fix the problem.

Best,
Chenglong

**Comment by vancleve** [comment] 2024-05-18 19:29
No prob:

<img width="667" alt="image" src="https://github.com/ChenglongMa/zoplicate/assets/1442334/3167c960-204f-4cc7-a7ed-fcc84be5f5b9">

**Comment by Cooperxjt** [comment] 2024-05-19 07:11
I have the same problem.

**Closed** 2024-07-12 04:34 UTC
